version: '3'
services: 
  django:
    image: buysell:0.6 
    ports:
      - 8000:8000
    env_file:
      - ./.DJANGO_SECRET_KEY
    volumes:
      - sqlyte:/home/django/mysite/
volumes:
  sqlyte:
    driver: local