# Generated by Django 4.0 on 2022-08-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_stripe_payment_intent_orderdetail_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='payment_intent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
