# Generated by Django 4.0 on 2022-08-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_orderdetail_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='404.png', upload_to='images'),
        ),
    ]
